#!/bin/bash

mysql -h yourendpoint -u admin -p <<EOF

CREATE DATABASE my_library;

CREATE USER 'my_library'@'%' IDENTIFIED BY 'nhipata_123';

GRANT ALL PRIVILEGES ON my_library.* TO 'my_library'@'%';

FLUSH PRIVILEGES;

EOF